
**SINTAXE BÁSICA DO PYTORCH**

Para mais informações:
https://pytorch.org/docs/stable/tensors.html

**Tipos de Tensores**

Você pode criar tensores de diversas formas. Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter listas comuns do python em tensors do PyTorch.

Note que a impressão de tensores dos tipos float32 e int64 não vem acompanhados do parâmetro dtype, visto que se tratam dos tipos padrão do PyTorch


In [4]:
import torch

lista = [[1,2,3],[4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


**Outra forma de instanciar arrays**

*torch.from_numpy()*


In [6]:
import numpy as np

arr = np.random.rand(3,4)

tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.80298866 0.64900521 0.68250609 0.24220417]
 [0.80150211 0.36501661 0.87717031 0.72267519]
 [0.00343363 0.96668609 0.95166106 0.62877638]]
float64
tensor([[0.8030, 0.6490, 0.6825, 0.2422],
        [0.8015, 0.3650, 0.8772, 0.7227],
        [0.0034, 0.9667, 0.9517, 0.6288]], dtype=torch.float64)
torch.float64


**Tensores Inicializados**

1.   *torch.ones()* -> Cria um tensor preenchido com uns.
2.   *torch.zeros()* -> Cria um tensor preenchido com zeros.
3.   *torch.randn()* -> Cria um tensor preenchido com numeros aleatores a partir de uma distribuição normal




In [7]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.6893,  0.7846,  0.2192],
        [-1.1047, -0.4082, -1.4120],
        [-1.7524, -1.2063,  1.6160]])


**Tensor para array numpy**



In [9]:
print(type(tnsr))
arr = tnsr.data.numpy()

print(type(arr))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


**Indexação**
De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de colchetes [].


In [11]:
print(tnsr)

tnsr[0,2] = -10

print(tnsr)



tensor([[ 0.6893,  0.7846,  0.2192],
        [-1.1047, -0.4082, -1.4120],
        [-1.7524, -1.2063,  1.6160]])
tensor([[  0.6893,   0.7846, -10.0000],
        [ -1.1047,  -0.4082,  -1.4120],
        [ -1.7524,  -1.2063,   1.6160]])


INDEXAR É ACESSAR UMA PARTE DO SEU TENSOR

In [12]:
print(tnsr)
tnsr[0,2] = -10
print('')
print(tnsr)

print('')
print(tnsr[:,2])

tensor([[  0.6893,   0.7846, -10.0000],
        [ -1.1047,  -0.4082,  -1.4120],
        [ -1.7524,  -1.2063,   1.6160]])

tensor([[  0.6893,   0.7846, -10.0000],
        [ -1.1047,  -0.4082,  -1.4120],
        [ -1.7524,  -1.2063,   1.6160]])

tensor([-10.0000,  -1.4120,   1.6160])


**Operações com tensores**

In [18]:
print(tnsr.shape)
print(tns1.shape)
print(tnsr)

tns = tnsr[0:2,:]

print(tns+tns1)

#A multiplicação é feita ponto a ponto, se você quiser a multiplicação de matrizes de fato, é necessário utilizar funções específicas do torch




torch.Size([3, 3])
torch.Size([2, 3])
tensor([[  0.6893,   0.7846, -10.0000],
        [ -1.1047,  -0.4082,  -1.4120],
        [ -1.7524,  -1.2063,   1.6160]])
tensor([[ 1.6893,  1.7846, -9.0000],
        [-0.1047,  0.5918, -0.4120]])


**.size e .view**

In [20]:
tns =  torch.randn(2,2,3)
print(tns)

print(tns.size())
tns = tns.view(12) #ou tns.view(-1)
print(tns)

tensor([[[ 1.3894,  1.5279, -0.5605],
         [ 0.2363, -0.0228,  0.8292]],

        [[-0.0478, -0.5837,  0.0316],
         [ 0.3601,  0.7700, -0.0520]]])
torch.Size([2, 2, 3])
tensor([ 1.3894,  1.5279, -0.5605,  0.2363, -0.0228,  0.8292, -0.0478, -0.5837,
         0.0316,  0.3601,  0.7700, -0.0520])


**GPU CAST**

O torch permite a utilização do gpu

In [2]:
import torch

tns = torch.randn(10)

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([-0.5137,  0.2921,  0.2106,  1.5120, -1.0775,  0.0401,  0.0914,  0.0655,
         0.3690, -1.6311], device='cuda:0')
